name: Go Build and Package

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'

      - name: Build
        run: |
          go build -v -o manthys .

      - name: Print GITHUB_SHA
        run: echo "GITHUB_SHA is $GITHUB_SHA"
  
      - name: Package Binary and Set TAR_FILE
        run: |
          echo "TAR_FILE=manthys-${GITHUB_SHA::8}.tar.gz" >> $GITHUB_ENV
          tar -czvf $TAR_FILE manthys
        shell: bash

      - name: Verify .tar.gz file exists
        run: |
          if test -f "$TAR_FILE"; then
              echo "$TAR_FILE exists."
          else
              echo "$TAR_FILE does not exist."
              exit 1
          fi

      - name: List files in current directory
        run: |
          pwd
          ls -la
        
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: manthys-binary-${GITHUB_SHA::8}.tar.gz
          path: ${{ env.TAR_FILE }}
